[IMP] stock_procurement_calendar_purchase: split and improme procurem…
acsone/stock-logistics-warehouse pull request #1
Opened 2018-03-21 15:14 UTC by tfossoulw

…ent attedance compute functions

2018-03-27 10:26 UTC, rousseldenis requested changes
Code review. Minor comment

2018-03-27 10:26 UTC, rousseldenis commented on stock_procurement_calendar_purchase/models/stock_warehouse_orderpoint.py
> +                attendances_to_look = daily_product_attendances.filtered(
'to_look' is not well appropriate I think. 'to_look_for'

2018-03-27 14:33 UTC, rousseldenis commented on stock_procurement_calendar_purchase/models/procurement.py
> +        self.mapped('orderpoint_id.procurement_calendar_id')
@tfo What's the aim here ?

2018-03-27 14:37 UTC, tfossoulw commented
@rousseldenis j'ai changé:

- self.mapped('orderpoint_id.procurement_calendar_id'): quand on lance le run scheduler, la premiere chose qu'il fait, c'est checker les procurement un par un. Le mapped précharge les datas et ça va bcp plus vite.
- j'ai rajouté un test pour le codecoverage. -> test pour un produit qui est lié a un calendrier sans supplier. mais avec un calendrier lié à un autre de sceduled date.
donc on va avoir un appro stock. 
le test: il faut juste vérifier qu'il va créer un proc order avec les qty correctes et qu'il est passé dans les bonnes boucles dans le code.
- j'ai retiré le code concernant le champ procurement_rule_id

2018-03-27 14:39 UTC, tfossoulw commented on stock_procurement_calendar_purchase/models/procurement.py
> +        self.mapped('orderpoint_id.procurement_calendar_id')
@rousseldenis check description below

2018-04-03 11:57 UTC, tfossoulw commented
@rousseldenis update: odoo will now skip attendance that have order date time lower than the now time.
ex: it will avoid to generate purchase order with an order date at 9h30 if the scheduler is launched à 1pm in the afternoon.

2018-06-01 07:41 UTC, rousseldenis commented
@tfossoulw Is this PR ready to be merged ?

2018-06-01 08:22 UTC, rousseldenis approved these changes

2018-06-01 08:22 UTC, merged